import {Injectable,NotFoundException} from '@nestjs/common'; import {NotificationType} from '@prisma/client'; import {PrismaService} from '../prisma/prisma.service';
@Injectable() export class NotificationsService{
 constructor(private readonly prisma:PrismaService){}
 private async pref(userId:string){return this.prisma.notificationPreference.upsert({where:{userId},create:{userId},update:{}});}
 async list(userId:string){return {data:await this.prisma.notification.findMany({where:{userId},orderBy:{createdAt:'desc'},take:100})};}
 async markRead(userId:string,id:string){const n=await this.prisma.notification.updateMany({where:{id,userId},data:{readAt:new Date()}});if(!n.count)throw new NotFoundException('Notification not found');return {read:true};}
 async preferences(userId:string){return {data:await this.pref(userId)};}
 async updatePreferences(userId:string,data:any){return {data:await this.prisma.notificationPreference.upsert({where:{userId},create:{userId,...data},update:data})};}
 async registerDevice(userId:string,data:{token:string;platform:string}){return {data:await this.prisma.pushDevice.upsert({where:{token:data.token},create:{userId,token:data.token,platform:data.platform},update:{userId,platform:data.platform,enabled:true,lastSeenAt:new Date()}})};}
 async unregisterDevice(userId:string,token:string){await this.prisma.pushDevice.updateMany({where:{userId,token},data:{enabled:false,lastSeenAt:new Date()}});return {disabled:true};}
 async create(userId:string,type:NotificationType,title:string,body:string,dedupeKey:string,bookingId?:string){const p=await this.pref(userId);const enabled=(p as any)[type.toLowerCase()+'Enabled'] ?? true;if(!enabled)return {data:null,suppressed:true};const existing=await this.prisma.notificationDelivery.findUnique({where:{dedupeKey}});if(existing)return {data:{id:existing.notificationId},deduplicated:true};const n=await this.prisma.notification.create({data:{userId,type,title,body,bookingId}});await this.prisma.notificationDelivery.create({data:{notificationId:n.id,userId,channel:'IN_APP',dedupeKey,status:'DELIVERED',deliveredAt:new Date(),attemptCount:1}});const devices=await this.prisma.pushDevice.findMany({where:{userId,enabled:true}});for(const d of devices){await this.prisma.notificationDelivery.create({data:{notificationId:n.id,userId,channel:'PUSH',dedupeKey:dedupeKey+':'+d.id,status:'PENDING',nextAttemptAt:new Date()}});}return {data:n};}
 async retryFailed(limit=100){const rows=await this.prisma.notificationDelivery.findMany({where:{status:'FAILED',attemptCount:{lt:5},OR:[{nextAttemptAt:null},{nextAttemptAt:{lte:new Date()}}]},take:limit});for(const row of rows){const attempts=row.attemptCount+1;await this.prisma.notificationDelivery.update({where:{id:row.id},data:{status:attempts>=5?'FAILED':'PENDING',attemptCount:attempts,nextAttemptAt:attempts>=5?null:new Date(Date.now()+Math.min(60_000*2**attempts,3_600_000)),lastError:attempts>=5?'MAX_RETRIES':'Push provider pending'}});}return {retried:rows.length};}
 async supportCreate(userId:string,b:{subject:string;description:string;category:string;priority?:string}){return {data:await this.prisma.supportTicket.create({data:{userId,...b}})};}
 async supportMine(userId:string){return {data:await this.prisma.supportTicket.findMany({where:{userId},orderBy:{createdAt:'desc'}})};}
 async deactivate(userId:string){return {data:await this.prisma.user.update({where:{id:userId},data:{status:'SUSPENDED',deactivatedAt:new Date()}})};}
 async requestDeletion(userId:string){const date=new Date(Date.now()+30*86400000);return {data:await this.prisma.user.update({where:{id:userId},data:{deletionRequestedAt:new Date(),deletionScheduledAt:date,status:'SUSPENDED',deactivatedAt:new Date()},select:{id:true,status:true,deletionRequestedAt:true,deletionScheduledAt:true}})};}
 async cancelDeletion(userId:string){return {data:await this.prisma.user.update({where:{id:userId},data:{deletionRequestedAt:null,deletionScheduledAt:null,status:'ACTIVE',deactivatedAt:null},select:{id:true,status:true}})};}
}
