def node_require(script)
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, '15.1'

prepare_react_native_project!

setup_permissions([
  'Camera',
  'LocationWhenInUse',
  'Microphone',
  'Notifications',
])

target 'Worko' do
  config = use_native_modules!

  use_react_native!(
    path: config[:reactNativePath],
    app_path: "#{Pod::Config.instance.installation_root}/..",
  )
end
