import React,{useCallback,useEffect,useState}from'react';
import{ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,View}from'react-native';
import AsyncStorage from'@react-native-async-storage/async-storage';
import{useNavigation}from'@react-navigation/native';
import type{BottomTabNavigationProp}from'@react-navigation/bottom-tabs';
import{useWorkoTheme}from'../../design-system/ThemeProvider';
import type{WorkerTabParamList}from'../../navigation/types';
import{apiRequest}from'../../services/api/client';

type State={available:boolean;offerCount:number;categoryCount:number;profileCompletion:number;radius:number;updated:boolean};
const ORANGE='#FF5A00';const GREEN='#10A63B';const PURPLE='#7A3FF2';

export function WorkerNoOffersScreen(){
 const{theme}=useWorkoTheme();const navigation=useNavigation<BottomTabNavigationProp<WorkerTabParamList>>();
 const[state,setState]=useState<State|null>(null);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);
 const load=useCallback(async()=>{const token=await AsyncStorage.getItem('worko.accessToken');if(!token){setLoading(false);return}try{const r=await apiRequest('/worker/dashboard',{headers:{Authorization:'Bearer '+token}});const p=await r.json().catch(()=>({}));if(r.ok&&p?.data){const d=p.data;setState({available:d.worker.availabilityStatus==='AVAILABLE',offerCount:d.counts.newOffers,categoryCount:d.worker.categoryCount,profileCompletion:d.worker.profileCompletion,radius:d.worker.preferredRadiusKm,updated:false})}}finally{setLoading(false);setRefreshing(false)}},[]);
 useEffect(()=>{void load();const t=setInterval(()=>void load(),8000);return()=>clearInterval(t)},[load]);
 if(loading)return<View style={[s.center,{backgroundColor:theme.background}]}><ActivityIndicator color={ORANGE}/><Text style={{color:theme.secondaryText,marginTop:10}}>Checking for offers…</Text></View>;
 const unavailable=state?.available===false;const noOffers=(state?.offerCount??0)===0;const incomplete=(state?.categoryCount??0)===0||(state?.profileCompletion??0)<80;
 const goPreferences=()=>navigation.navigate('Preferences');const goAvailability=()=>navigation.navigate('Availability');
 return<View style={{flex:1,backgroundColor:theme.background}}><ScrollView contentContainerStyle={s.container}>
  <View style={s.header}><Text style={s.brand}>Worko</Text><Pressable onPress={()=>navigation.goBack()}><Text style={[s.close,{color:theme.text}]}>×</Text></Pressable></View>
  <View style={s.hero}><Text style={s.heroIcon}>{unavailable?'⊗':noOffers?'⌕':'✓'}</Text><Text style={[s.heroTitle,{color:theme.text}]}>{unavailable?'You are currently unavailable':state?.updated?'All set!':noOffers?'No offers yet':'No offers match right now'}</Text><Text style={[s.heroText,{color:theme.secondaryText}]}>{unavailable?'You will not receive new work offers while you are unavailable.':state?.updated?'Your preferences have been updated. We’ll notify you when new offers match your criteria.':noOffers?'We’ll notify you here when new work offers match your skills, location and preferences.':'We couldn’t find any offers that match your current preferences.'}</Text></View>
  {unavailable?<><Pressable onPress={goAvailability} style={s.primary}><Text style={s.primaryText}>Go Available</Text></Pressable><View style={s.info}><Text style={s.infoIcon}>i</Text><Text style={[s.infoText,{color:theme.secondaryText}]}>You can change your availability anytime from the Home screen.</Text></View></>:state?.updated? <Pressable onPress={()=>{setState(x=>x?{...x,updated:false}:x);void load()}} style={s.primary}><Text style={s.primaryText}>Back to Offers</Text></Pressable>:<><Text style={[s.section,{color:theme.text}]}>{noOffers?'Here are a few ways to improve your chances of receiving offers.':'Try adjusting your preferences'}</Text>
   <Suggestion icon="▣" title="Update Work Preferences" description="Add or edit the types of work you want to receive." onPress={goPreferences} theme={theme}/>
   <Suggestion icon="●" title="Increase Service Radius" description={state?.radius===25?'Your radius is already at 25 km.':'You can receive offers from nearby areas.'} onPress={goPreferences} theme={theme}/>
   <Suggestion icon="▦" title="Check Availability" description={state?.available?'You are marked as available.':'Make sure you are marked as available.'} onPress={goAvailability} theme={theme}/>
   {incomplete?<Suggestion icon="●" title="Complete Your Profile" description="A complete profile helps you get more offers." onPress={()=>navigation.navigate('Profile')} theme={theme}/>:null}
   {!noOffers?<View style={s.matchCard}><Text style={[s.matchTitle,{color:theme.text}]}>Try adjusting your preferences</Text><Text style={[s.matchText,{color:theme.secondaryText}]}>Increase your radius or add more work categories to broaden matching.</Text></View>:null}
  </>}
  </ScrollView></View>
}
function Suggestion({icon,title,description,onPress,theme}:{icon:string;title:string;description:string;onPress:()=>void;theme:any}){return<Pressable onPress={onPress} style={[s.suggestion,{backgroundColor:theme.surface,borderColor:theme.border}]}><View style={s.suggestionIcon}><Text style={s.suggestionIconText}>{icon}</Text></View><View style={{flex:1}}><Text style={[s.suggestionTitle,{color:theme.text}]}>{title}</Text><Text style={[s.suggestionText,{color:theme.secondaryText}]}>{description}</Text></View><Text style={s.chevron}>›</Text></Pressable>}
const s=StyleSheet.create({container:{padding:22,paddingBottom:40},center:{flex:1,alignItems:'center',justifyContent:'center'},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:22},brand:{color:ORANGE,fontSize:27,fontWeight:'900'},close:{fontSize:30,fontWeight:'300'},hero:{alignItems:'center',paddingTop:55,paddingHorizontal:18,paddingBottom:28},heroIcon:{fontSize:62,color:ORANGE,marginBottom:20},heroTitle:{fontSize:21,fontWeight:'900',textAlign:'center',marginBottom:8},heroText:{fontSize:14,lineHeight:21,textAlign:'center'},primary:{minHeight:50,borderRadius:11,backgroundColor:ORANGE,alignItems:'center',justifyContent:'center',marginTop:8},primaryText:{color:'#FFF',fontSize:14,fontWeight:'900'},info:{marginTop:12,backgroundColor:'#F2F7FF',borderRadius:12,padding:13,flexDirection:'row',alignItems:'center'},infoIcon:{width:24,height:24,borderRadius:12,backgroundColor:'#8C99AA',color:'#FFF',textAlign:'center',lineHeight:24,fontWeight:'900',marginRight:9},infoText:{flex:1,fontSize:12,lineHeight:18},section:{fontSize:17,fontWeight:'900',marginBottom:10},suggestion:{minHeight:83,borderWidth:1,borderRadius:14,padding:12,flexDirection:'row',alignItems:'center',marginBottom:9},suggestionIcon:{width:44,height:44,borderRadius:22,backgroundColor:'#FFF1E6',alignItems:'center',justifyContent:'center',marginRight:11},suggestionIconText:{color:ORANGE,fontSize:19,fontWeight:'900'},suggestionTitle:{fontSize:14,fontWeight:'900',marginBottom:4},suggestionText:{fontSize:11,lineHeight:17},chevron:{fontSize:28,color:ORANGE,marginLeft:8},matchCard:{marginTop:5,borderRadius:13,backgroundColor:'#F7F4FF',padding:14},matchTitle:{fontSize:14,fontWeight:'900',marginBottom:4},matchText:{fontSize:12,lineHeight:18}});
