import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { launchImageLibrary } from 'react-native-image-picker';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useWorkoTheme } from '../../design-system/ThemeProvider';
import { apiRequest } from '../../services/api/client';

type Reel={id:string;caption?:string;moderationStatus:string;viewCount:number;likeCount:number;shareCount:number;mediaUrl:string;publishedAt?:string|null;rejectionReason?:string|null};
type Challenge={id:string;title:string;description:string;rewardPoints:number;startsAt?:string|null;endsAt?:string|null;participantCount:number;participation?:{status:string}|null};

export function WorkerReelStudioScreen(){
 const {theme}=useWorkoTheme(); const [reels,setReels]=useState<Reel[]>([]); const [challenges,setChallenges]=useState<Challenge[]>([]);
 const [caption,setCaption]=useState(''); const [categoryId,setCategoryId]=useState(''); const [categories,setCategories]=useState<{id:string;name:string}[]>([]);
 const [video,setVideo]=useState<any>(null); const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(true);
 const tokenRef=React.useRef<string|null>(null);
 const load=async()=>{const token=await AsyncStorage.getItem('worko.accessToken');tokenRef.current=token;if(!token)return;try{const [r,c,cat]=await Promise.all([apiRequest('/reels/mine',{headers:{Authorization:`Bearer ${token}`}}),apiRequest('/challenges',{headers:{Authorization:`Bearer ${token}`}}),apiRequest('/categories')]);const rp=await r.json();const cp=await c.json();const kp=await cat.json();setReels(rp.data??[]);setChallenges(cp.data??[]);setCategories(kp.data??[]);}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const pick=async()=>{const result=await launchImageLibrary({mediaType:'video',selectionLimit:1,videoQuality:'high'});if(result.didCancel||!result.assets?.[0]?.uri)return;setVideo(result.assets[0]);};
 const upload=async()=>{if(!video?.uri||!tokenRef.current)return;setBusy(true);try{const form=new FormData();form.append('video',{uri:video.uri,name:video.fileName||'worko-reel.mp4',type:video.type||'video/mp4'} as any);form.append('caption',caption);if(categoryId)form.append('categoryId',categoryId);const r=await apiRequest('/reels/upload',{method:'POST',headers:{Authorization:`Bearer ${tokenRef.current}`},body:form as any});const p=await r.json();if(!r.ok)throw new Error(p.message||'Upload failed');Alert.alert('Uploaded','Your reel is submitted for moderation.');setVideo(null);setCaption('');await load();}catch(e){Alert.alert('Upload failed',e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}};
 const publish=async(id:string)=>{if(!tokenRef.current)return;const r=await apiRequest(`/reels/${id}/publish`,{method:'POST',headers:{Authorization:`Bearer ${tokenRef.current}`}});if(!r.ok){const p=await r.json().catch(()=>({}));Alert.alert('Cannot publish',p.message||'Try again.');return;}await load();};
 const join=async(id:string)=>{if(!tokenRef.current)return;const r=await apiRequest(`/challenges/${id}/join`,{method:'POST',headers:{Authorization:`Bearer ${tokenRef.current}`}});if(!r.ok){const p=await r.json().catch(()=>({}));Alert.alert('Challenge',p.message||'Unable to join.');return;}await load();};
 return <ScrollView style={{flex:1,backgroundColor:theme.background}} contentContainerStyle={styles.page}>
  <Text style={[styles.title,{color:theme.text}]}>Reel Studio</Text><Text style={[styles.sub,{color:theme.secondaryText}]}>Create, publish and track your professional work videos.</Text>
  <View style={[styles.card,{backgroundColor:theme.surface,borderColor:theme.border}]}><Text style={[styles.head,{color:theme.text}]}>Create reel</Text><Pressable onPress={()=>void pick()} style={[styles.button,{backgroundColor:theme.primary}]}><Text style={styles.buttonText}>{video?'Change video':'Select video'}</Text></Pressable>{video?<Text style={[styles.meta,{color:theme.secondaryText}]}>{video.fileName||'Selected video'}</Text>:null}<TextInput value={caption} onChangeText={setCaption} maxLength={2200} multiline placeholder="Write a caption…" placeholderTextColor={theme.secondaryText} style={[styles.input,{color:theme.text,borderColor:theme.border}]}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8}}>{categories.map(x=><Pressable key={x.id} onPress={()=>setCategoryId(x.id)} style={[styles.chip,{borderColor:theme.border,backgroundColor:categoryId===x.id?theme.primary:theme.surface}]}><Text style={{color:categoryId===x.id?'#FFF':theme.text,fontWeight:'700'}}>{x.name}</Text></Pressable>)}</ScrollView><Pressable disabled={!video||busy} onPress={()=>void upload()} style={[styles.button,{backgroundColor:theme.primary,opacity:!video||busy?.5:1}]}><Text style={styles.buttonText}>{busy?'Uploading…':'Upload for moderation'}</Text></Pressable></View>
  <Text style={[styles.section,{color:theme.text}]}>My reels</Text>{loading?<ActivityIndicator color={theme.primary}/>:reels.length===0?<Text style={[styles.sub,{color:theme.secondaryText}]}>No reels yet.</Text>:reels.map(r=><View key={r.id} style={[styles.card,{backgroundColor:theme.surface,borderColor:theme.border}]}><Text style={[styles.head,{color:theme.text}]}>{r.caption||'Untitled reel'}</Text><Text style={[styles.meta,{color:theme.secondaryText}]}>Status: {r.moderationStatus} · {r.viewCount} views · {r.likeCount} likes · {r.shareCount} shares</Text>{r.rejectionReason?<Text style={{color:theme.primary}}>Reason: {r.rejectionReason}</Text>:null}{r.moderationStatus==='APPROVED'&&!r.publishedAt?<Pressable onPress={()=>void publish(r.id)} style={[styles.button,{backgroundColor:theme.primary}]}><Text style={styles.buttonText}>Publish</Text></Pressable>:null}</View>)}
  <Text style={[styles.section,{color:theme.text}]}>Challenges</Text>{challenges.map(ch=><View key={ch.id} style={[styles.card,{backgroundColor:theme.surface,borderColor:theme.border}]}><Text style={[styles.head,{color:theme.text}]}>{ch.title}</Text><Text style={[styles.meta,{color:theme.secondaryText}]}>{ch.description}</Text><Text style={[styles.meta,{color:theme.primary,fontWeight:'800'}]}>+{ch.rewardPoints} points · {ch.participantCount} participants</Text>{ch.participation?<Text style={{color:theme.secondaryText}}>Joined</Text>:<Pressable onPress={()=>void join(ch.id)} style={[styles.button,{backgroundColor:theme.primary}]}><Text style={styles.buttonText}>Join challenge</Text></Pressable>}</View>)}
 </ScrollView>;
}
const styles=StyleSheet.create({page:{padding:20,paddingBottom:40},title:{fontSize:28,fontWeight:'900'},sub:{fontSize:14,lineHeight:21,marginTop:5,marginBottom:16},section:{fontSize:20,fontWeight:'900',marginTop:22,marginBottom:10},card:{borderWidth:1,borderRadius:16,padding:16,marginBottom:12},head:{fontSize:16,fontWeight:'900',marginBottom:7},meta:{fontSize:13,lineHeight:20,marginBottom:8},button:{minHeight:46,borderRadius:12,alignItems:'center',justifyContent:'center',paddingHorizontal:16,marginTop:10},buttonText:{color:'#FFF',fontWeight:'900'},input:{minHeight:90,borderWidth:1,borderRadius:12,padding:12,marginTop:12,textAlignVertical:'top'},chip:{borderWidth:1,borderRadius:20,paddingHorizontal:13,paddingVertical:8}});