import React,{useCallback,useEffect,useState} from 'react';
import {Alert,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View} from 'react-native';
import {apiRequest} from '../../services/api/client';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {useWorkoTheme} from '../../design-system/ThemeProvider';

type Section='dashboard'|'users'|'verification'|'matching'|'bookings'|'payments'|'disputes'|'safety'|'reels'|'challenges'|'analytics'|'audit'|'health'|'config'|'wallets'|'support'|'notifications';
const sections: Array<{id:Section;label:string}>=[
 {id:'dashboard',label:'Overview'},{id:'users',label:'Users'},{id:'verification',label:'Verification'},{id:'matching',label:'Matching'},{id:'bookings',label:'Bookings'},{id:'payments',label:'Payments'},{id:'wallets',label:'Wallets'},{id:'disputes',label:'Disputes'},{id:'safety',label:'Safety'},{id:'reels',label:'Reel moderation'},{id:'challenges',label:'Challenges'},{id:'analytics',label:'Analytics'},{id:'audit',label:'Audit logs'},{id:'health',label:'System health'},{id:'config',label:'Configuration'},{id:'support',label:'Support'},{id:'notifications',label:'Notification ops'},
];
export function AdminExperienceScreen(){
 const {theme}=useWorkoTheme(); const [section,setSection]=useState<Section>('dashboard'); const [data,setData]=useState<any>(null); const [loading,setLoading]=useState(true);
 const load=useCallback(async(s:Section)=>{setLoading(true);try{const token=await AsyncStorage.getItem('worko.accessToken');const path=s==='dashboard'?'dashboard':s==='notifications'?'health':s;const res=await apiRequest('/admin/'+path,{headers:{Authorization:'Bearer '+token}});const p=await res.json();if(!res.ok)throw new Error(p.message||'Admin request failed');setData(p.data);}catch(e){Alert.alert('Admin error',e instanceof Error?e.message:'Unable to load admin data.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load(section)},[section,load]);
 const action=async(path:string,method:'PATCH'|'POST',body:any)=>{try{const token=await AsyncStorage.getItem('worko.accessToken');const res=await apiRequest(path,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(body)});const p=await res.json();if(!res.ok)throw new Error(p.message||'Action failed');await load(section)}catch(e){Alert.alert('Action failed',e instanceof Error?e.message:'Try again.')}};
 const renderValue=(v:any):React.ReactNode=>{if(v===null||v===undefined)return '—';if(typeof v==='object')return JSON.stringify(v);return String(v)};
 return <View style={{flex:1,backgroundColor:theme.background}}>
  <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.tabs}>{sections.map(x=><Pressable key={x.id} onPress={()=>setSection(x.id)} style={[s.tab,{backgroundColor:section===x.id?theme.primary:theme.surface,borderColor:theme.border}]}><Text style={{color:section===x.id?'#FFF':theme.text,fontWeight:'800',fontSize:12}}>{x.label}</Text></Pressable>)}</ScrollView>
  <ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={()=>void load(section)}/>} contentContainerStyle={s.content}>
   <Text style={[s.title,{color:theme.text}]}>{sections.find(x=>x.id===section)?.label}</Text>
   {section==='dashboard'&&data&&<View style={s.grid}>{[['Users',data.users],['Pending workers',data.workersPending],['Active requests',data.activeRequirements],['Active bookings',data.activeBookings],['Held payments','₹'+renderValue(data.heldPayments)],['Open disputes',data.openDisputes],['Safety alerts',data.openSafetyAlerts],['Pending reels',data.pendingReels]].map(([k,v])=><View key={String(k)} style={[s.card,{backgroundColor:theme.surface,borderColor:theme.border}]}><Text style={{color:theme.secondaryText}}>{k}</Text><Text style={[s.metric,{color:theme.text}]}>{renderValue(v)}</Text></View>)}</View>}
   {section!=='dashboard'&&Array.isArray(data)&&data.map((row:any,i:number)=><View key={row.id??i} style={[s.row,{backgroundColor:theme.surface,borderColor:theme.border}]}><Text style={[s.rowTitle,{color:theme.text}]}>{row.title||row.email||row.id||row.type||row.action||row.key||'Record'}</Text><Text style={{color:theme.secondaryText,lineHeight:19}}>{Object.entries(row).slice(0,7).map(([k,v])=>k+': '+renderValue(v)).join('\n')}</Text>{section==='verification'&&<View style={s.actions}><Pressable onPress={()=>void action('/admin/verification/'+row.id,'PATCH',{status:'VERIFIED'})} style={s.ok}><Text style={s.actionText}>Approve</Text></Pressable><Pressable onPress={()=>void action('/admin/verification/'+row.id,'PATCH',{status:'REJECTED'})} style={s.danger}><Text style={s.actionText}>Reject</Text></Pressable></View>}{section==='reels'&&<View style={s.actions}><Pressable onPress={()=>void action('/admin/reels/'+row.id,'PATCH',{status:'APPROVED'})} style={s.ok}><Text style={s.actionText}>Approve</Text></Pressable><Pressable onPress={()=>void action('/admin/reels/'+row.id,'PATCH',{status:'REJECTED'})} style={s.danger}><Text style={s.actionText}>Reject</Text></Pressable></View>}{section==='disputes'&&<Pressable onPress={()=>void action('/admin/disputes/'+row.id,'PATCH',{status:'RESOLVED'})} style={s.ok}><Text style={s.actionText}>Resolve</Text></Pressable>}{section==='safety'&&<Pressable onPress={()=>void action('/admin/safety/'+row.id,'PATCH',{status:'RESOLVED'})} style={s.danger}><Text style={s.actionText}>Resolve safety alert</Text></Pressable>}</View>)}
   {section==='users'&&Array.isArray(data)&&data.map((row:any)=><Pressable key={row.id} onPress={()=>Alert.alert('Account control','Suspend or restore this account?', [{text:'Cancel'},{text:'Suspend',style:'destructive',onPress:()=>void action('/admin/users/'+row.id+'/status','PATCH',{status:'SUSPENDED'})},{text:'Activate',onPress:()=>void action('/admin/users/'+row.id+'/status','PATCH',{status:'ACTIVE'})}])} style={[s.row,{backgroundColor:theme.surface,borderColor:theme.border}]}><Text style={[s.rowTitle,{color:theme.text}]}>{row.email||row.phone||row.id}</Text><Text style={{color:theme.secondaryText}}>{row.role} · {row.status}</Text></Pressable>)}
   {section==='health'&&data&&<View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.border}]}>{Object.entries(data).map(([k,v])=><Text key={k} style={{color:theme.text,marginBottom:8}}>{k}: {renderValue(v)}</Text>)}</View>}
   {section==='analytics'&&data&&<View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.border}]}>{Object.entries(data).map(([k,v])=><Text key={k} style={{color:theme.text,marginBottom:10}}>{k}: {renderValue(v)}</Text>)}</View>}
   {section==='config'&&<View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.border}]}><Text style={{color:theme.secondaryText}}>Configuration is intentionally API-controlled. Use the admin configuration endpoints to change operational flags without shipping a new app.</Text></View>}
   {section==='notifications'&&<View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.border}]}><Text style={{color:theme.text,fontWeight:'800',marginBottom:8}}>Notification delivery</Text><Text style={{color:theme.secondaryText}}>In-app delivery, device registration, deduplication and retry queue are enabled. Push provider delivery is isolated behind the delivery queue so provider credentials never enter the mobile app.</Text></View>}
   {!loading&&data===null&&section!=='dashboard'&&<Text style={{color:theme.secondaryText}}>No data returned.</Text>}
  </ScrollView>
 </View>
}
const s=StyleSheet.create({tabs:{padding:12,gap:8},tab:{paddingHorizontal:13,paddingVertical:10,borderRadius:18,borderWidth:1},content:{padding:16,paddingBottom:40},title:{fontSize:28,fontWeight:'900',marginBottom:16},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},card:{borderWidth:1,borderRadius:16,padding:16,marginBottom:12,flex:1,minWidth:'46%'},metric:{fontSize:25,fontWeight:'900',marginTop:8},row:{borderWidth:1,borderRadius:16,padding:15,marginBottom:10},rowTitle:{fontSize:15,fontWeight:'900',marginBottom:6},actions:{flexDirection:'row',gap:8,marginTop:12},ok:{backgroundColor:'#176B45',paddingHorizontal:15,paddingVertical:10,borderRadius:10},danger:{backgroundColor:'#A52828',paddingHorizontal:15,paddingVertical:10,borderRadius:10},actionText:{color:'#FFF',fontWeight:'900'}});
