import React,{useEffect,useState} from 'react';
import {Alert,Pressable,ScrollView,StyleSheet,Switch,Text,TextInput,View} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {apiRequest} from '../../services/api/client';
import {useWorkoTheme} from '../../design-system/ThemeProvider';

export function AccountManagementScreen(){
 const {theme}=useWorkoTheme();
 const [notes,setNotes]=useState<any[]>([]);
 const [prefs,setPrefs]=useState<any>({pushEnabled:true,bookingEnabled:true,paymentEnabled:true,chatEnabled:true,reviewEnabled:true,disputeEnabled:true,systemEnabled:true});
 const [subject,setSubject]=useState(''); const [description,setDescription]=useState('');
 const request=async(path:string,init?:RequestInit)=>{const t=await AsyncStorage.getItem('worko.accessToken');const r=await apiRequest(path,{...init,headers:{'Content-Type':'application/json',Authorization:'Bearer '+t}});const p=await r.json();if(!r.ok)throw new Error(p.message||'Request failed');return p;};
 useEffect(()=>{void request('/notifications').then(p=>setNotes(p.data||[])).catch(()=>{});void request('/notification-preferences').then(p=>setPrefs(p.data||prefs)).catch(()=>{});},[]);
 const save=async(k:string,v:boolean)=>{const next={...prefs,[k]:v};setPrefs(next);try{await request('/notification-preferences',{method:'PATCH',body:JSON.stringify(next)})}catch(e){Alert.alert('Preferences failed',e instanceof Error?e.message:'Try again.')}};
 const support=async()=>{if(!subject.trim()||!description.trim())return Alert.alert('Add details','Enter a subject and description.');try{await request('/support/tickets',{method:'POST',body:JSON.stringify({subject,description,category:'GENERAL',priority:'NORMAL'})});setSubject('');setDescription('');Alert.alert('Support request sent','Your ticket is open.')}catch(e){Alert.alert('Support failed',e instanceof Error?e.message:'Try again.')}};
 const action=async(path:string)=>{try{await request(path,{method:'POST'});Alert.alert('Request saved','Your account request has been recorded.')}catch(e){Alert.alert('Action failed',e instanceof Error?e.message:'Try again.')}};
 return <ScrollView style={{flex:1,backgroundColor:theme.background}} contentContainerStyle={s.content}>
 <Text style={[s.title,{color:theme.text}]}>Notifications & account</Text><Text style={[s.sub,{color:theme.secondaryText}]}>Manage delivery preferences, support, and account controls.</Text>
 <Text style={[s.heading,{color:theme.text}]}>Notification preferences</Text>{Object.keys(prefs).filter(k=>k.endsWith('Enabled')).map(k=><View key={k} style={[s.row,{borderColor:theme.border,backgroundColor:theme.surface}]}><Text style={{color:theme.text,fontWeight:'700'}}>{k.replace('Enabled','')}</Text><Switch value={Boolean(prefs[k])} onValueChange={v=>void save(k,v)}/></View>)}
 <Text style={[s.heading,{color:theme.text}]}>Recent notifications</Text>{notes.slice(0,15).map(n=><View key={n.id} style={[s.card,{backgroundColor:theme.surface,borderColor:theme.border}]}><Text style={[s.cardTitle,{color:theme.text}]}>{n.title}</Text><Text style={{color:theme.secondaryText}}>{n.body}</Text></View>)}
 <Text style={[s.heading,{color:theme.text}]}>Help & support</Text><TextInput placeholder="Subject" placeholderTextColor="#999" value={subject} onChangeText={setSubject} style={[s.input,{color:theme.text,borderColor:theme.border}]}/><TextInput placeholder="Describe the issue" placeholderTextColor="#999" multiline value={description} onChangeText={setDescription} style={[s.input,{color:theme.text,borderColor:theme.border,minHeight:100,textAlignVertical:'top'}]}/><Pressable onPress={()=>void support()} style={s.primary}><Text style={s.primaryText}>Create support ticket</Text></Pressable>
 <Text style={[s.heading,{color:theme.text}]}>Account controls</Text><Pressable onPress={()=>Alert.alert('Deactivate account','Your account will be suspended.',[{text:'Cancel'},{text:'Continue',style:'destructive',onPress:()=>void action('/account/deactivate')}])} style={[s.secondary,{borderColor:theme.border}]}><Text style={{color:theme.text,fontWeight:'800'}}>Deactivate account</Text></Pressable><Pressable onPress={()=>Alert.alert('Data deletion','Deletion is scheduled after a 30-day retention window.',[{text:'Cancel'},{text:'Request',style:'destructive',onPress:()=>void action('/account/deletion')}])} style={s.danger}><Text style={s.primaryText}>Request data deletion</Text></Pressable>
 </ScrollView>;
}
const s=StyleSheet.create({content:{padding:18,paddingBottom:40},title:{fontSize:28,fontWeight:'900',marginBottom:7},sub:{fontSize:14,lineHeight:21,marginBottom:20},heading:{fontSize:18,fontWeight:'900',marginTop:14,marginBottom:10},row:{minHeight:54,borderWidth:1,borderRadius:13,paddingHorizontal:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:8},card:{borderWidth:1,borderRadius:14,padding:14,marginBottom:8},cardTitle:{fontWeight:'900',marginBottom:4},input:{borderWidth:1,borderRadius:12,padding:13,marginBottom:9,fontSize:14},primary:{backgroundColor:'#FF6B00',minHeight:48,borderRadius:12,alignItems:'center',justifyContent:'center'},primaryText:{color:'#FFF',fontWeight:'900'},secondary:{minHeight:48,borderWidth:1,borderRadius:12,alignItems:'center',justifyContent:'center',marginBottom:8},danger:{backgroundColor:'#A52828',minHeight:48,borderRadius:12,alignItems:'center',justifyContent:'center'}});
